name: Python Style Checker

on:
  pull_request:
    branches: main
    types: [ opened, reopened, edited, synchronize ]
    paths: [ '**.py' ]

jobs:
  python-style-checker:
    name: Check pull request Python Style Checker
    runs-on: [ ubuntu-lastest ]
    steps:
      - uses: actions/checkout@v3
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
  
