name: Python Style Checker

on:
  pull_request:

jobs:
  python-style-checker:
    name: Check pull request Python Style Checker
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
