name: Python Style Checker

on:
  pull_request:
    branches: master
    types: [ opened, reopened, synchronize ]
    paths: [ '**.py' ]

jobs:
  python-style-checker:
    name: Check pull request Python Style Checker
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: actions/checkout@v3
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
  
